### ISSUE TITLE
Authentication is failed in Microsoft Edge Browser

### ISSUE THREAD

**Issue by sujathaSahadevan** [UnitedPlanet/intrexx-sample-oauth2-oidc-login-module#1]
Hi Team, 

The  SSO Authentication is Successfully  implemented and tested in UAT environment  and working well in  Edge, Chrome and IE. But in production environment,  the same configurations are used, except the Azure Client ID & client secret are different. 
But the Authentication is failed in Edge, but working in chrome and IE. When  try to investigate with the trouble shooting steps, the below error occurs for authentication fail case and the user credentials are not appearing in the portal.log file
since this is production portal, unable to enable the SSO frequently for testing. please see the error below.

**" Error while processing the OAuth2 callback request.
java.lang.IllegalArgumentException: Unsupported parameters, expected oauthprovider or code and state."**

and the detail log is available below

INFO  2021-02-19T17:07:41,236Z - de.uplanet.lucy.server.auth.module.anonymous.AnonymousLoginModule[http-nio-127.0.0.1-1338-exec-5]
 Try to login the anonymous user.
INFO  2021-02-19T17:07:41,270Z - de.uplanet.lucy.server.auth.module.anonymous.AnonymousLoginModule[http-nio-127.0.0.1-1338-exec-5]
 Adding the anonymous user principals to the subject.
DEBUG 2021-02-19T17:07:50,936Z - de.uplanet.lucy.server.composer.ixservlet.OAuth2LoginIxServlet[http-nio-127.0.0.1-1338-exec-4]
 
ERROR 2021-02-19T17:07:52,459Z - de.uplanet.lucy.server.composer.ixservlet.OAuth2LoginIxServlet[http-nio-127.0.0.1-1338-exec-10]
 Error while processing the OAuth2 callback request.
java.lang.IllegalArgumentException: Unsupported parameters, expected oauthprovider or code and state.
	at de.uplanet.lucy.server.composer.ixservlet.OAuth2LoginIxServlet.service(Unknown Source) [update/:?]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline.invokeServlet(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline$IIxFilterChainImpl.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.LogIxFilter.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline$IIxFilterChainImpl.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.SendMailIxFilter.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline$IIxFilterChainImpl.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.ProcessActionsIxFilter.doFilter(Unknown Source) [update/:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline$IIxFilterChainImpl.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.RestoreViewIxFilter.doFilter(Unknown Source) [update/:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline$IIxFilterChainImpl.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.flashscope.FlashScopeIxFilter.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline$IIxFilterChainImpl.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.ValidateRequestIxFilter.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline$IIxFilterChainImpl.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.BindSessionIxFilter$1.run(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at javax.security.auth.Subject.doAsPrivileged(Subject.java:484) [?:?]
	at de.uplanet.lucy.server.engine.http.BindSessionIxFilter.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline$IIxFilterChainImpl.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.SessionInfoIxFilter.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline$IIxFilterChainImpl.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.RequestPreparationFilter.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline$IIxFilterChainImpl.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.KerberosSupportIxFilter.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline$IIxFilterChainImpl.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.ThreadContextAndTransactionIxFilter.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline$IIxFilterChainImpl.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.ProtocolInformationIxFilter.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline$IIxFilterChainImpl.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.SetDefaultResponseCharsetIxFilter.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline$IIxFilterChainImpl.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.RequestCleanupFilter.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline$IIxFilterChainImpl.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.PingIxFilter.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline$IIxFilterChainImpl.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.DebugIxFilter.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline$IIxFilterChainImpl.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.engine.http.HttpRequestProcessingPipeline.process(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.webconnector.v2.servlet.ConnectorServlet._processRequest(Unknown Source) [ix-server-webconnector.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.webconnector.v2.servlet.ConnectorServlet.doGet(Unknown Source) [ix-server-webconnector.jar:9.2.0.20190423.195621]
	at de.uplanet.lucy.server.webconnector.v2.servlet.ConnectorServlet.service(Unknown Source) [ix-server-webconnector.jar:9.2.0.20190423.195621]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at de.uplanet.lucy.server.connector.servlet.ExternalAuthenticationFilter.doFilter(Unknown Source) [ix-server.jar:9.2.0.20190423.195621]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.filters.RemoteIpFilter.doFilter(RemoteIpFilter.java:921) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.filters.RemoteIpFilter.doFilter(RemoteIpFilter.java:978) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at de.uplanet.lucy.server.webconnector.v2.servlet.HeaderSecurityFilter.doFilter(Unknown Source) [ix-server-webconnector.jar:9.2.0.20190423.195621]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:186) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:668) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.50-patched.jar:8.5.50]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by manr** [comment]
Cannot reproduce this issue.
